programs:
    tail:
        cmd: "/usr/bin/tail -f /tmp/toto"
        numprocs: 2
        umask: 022
        workingdir: /tmp
        autostart: true
        autorestart: unexpected
        exitcodes:
            - 0
            - 2
            - -15
        startretries: 3
        starttime: 5
        stopsignal: TERM
        stoptime: 10
        stdout: /tmp/tail.stdout
        stderr: /tmp/tail.stderr
        env:
            STARTED_BY: taskmaster
            ANSWER: 42
    ls:
        cmd: "ls"
        numprocs: 1
        umask: 077
        workingdir: /tmp
        autostart: true
        autorestart: false
        exitcodes: 0
        startretries: 3
        starttime: 0
        stopsignal: USR1
        stoptime: 10
        stdout: /tmp/ls.stdout
        stderr: /tmp/ls.stderr
        redirect_stderr: true
